package com.potato.entity.charizard;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Index {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.dc_id
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private Integer dcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_uuid
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String indexUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_name
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_code
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String indexCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_version
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String indexVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.index_units
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String indexUnits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.unit_type
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String unitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.create_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.update_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.create_time
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index.datachange_lasttime
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.dc_id
     *
     * @return the value of index.dc_id
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public Integer getDcId() {
        return dcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.dc_id
     *
     * @param dcId the value for index.dc_id
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setDcId(Integer dcId) {
        this.dcId = dcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_uuid
     *
     * @return the value of index.index_uuid
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getIndexUuid() {
        return indexUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_uuid
     *
     * @param indexUuid the value for index.index_uuid
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setIndexUuid(String indexUuid) {
        this.indexUuid = indexUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_name
     *
     * @return the value of index.index_name
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_name
     *
     * @param indexName the value for index.index_name
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_code
     *
     * @return the value of index.index_code
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getIndexCode() {
        return indexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_code
     *
     * @param indexCode the value for index.index_code
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setIndexCode(String indexCode) {
        this.indexCode = indexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_version
     *
     * @return the value of index.index_version
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getIndexVersion() {
        return indexVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_version
     *
     * @param indexVersion the value for index.index_version
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setIndexVersion(String indexVersion) {
        this.indexVersion = indexVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.index_units
     *
     * @return the value of index.index_units
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getIndexUnits() {
        return indexUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.index_units
     *
     * @param indexUnits the value for index.index_units
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setIndexUnits(String indexUnits) {
        this.indexUnits = indexUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.unit_type
     *
     * @return the value of index.unit_type
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.unit_type
     *
     * @param unitType the value for index.unit_type
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setUnitType(String unitType) {
        this.unitType = unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.create_user
     *
     * @return the value of index.create_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.create_user
     *
     * @param createUser the value for index.create_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.update_user
     *
     * @return the value of index.update_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.update_user
     *
     * @param updateUser the value for index.update_user
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.create_time
     *
     * @return the value of index.create_time
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.create_time
     *
     * @param createTime the value for index.create_time
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index.datachange_lasttime
     *
     * @return the value of index.datachange_lasttime
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index.datachange_lasttime
     *
     * @param datachangeLasttime the value for index.datachange_lasttime
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}