package com.potato.mapper.charizard;

import com.potato.entity.charizard.Index;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface IndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    int deleteByPrimaryKey(Integer dcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    int insert(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    int insertSelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    Index selectByPrimaryKey(Integer dcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    int updateByPrimaryKeySelective(Index record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index
     *
     * @mbg.generated Thu Jun 24 20:33:07 CST 2021
     */
    int updateByPrimaryKey(Index record);

    List<Index> selectByIndexUuid(Index index);
}